modify assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -17,4 +17,13 @@ pip install powershift-cli[image]
 # Run the build phase with support for action hooks.
 
 #exec powershift image assemble
-exec /opt/app-root/s2i/assemble
+#exec /opt/app-root/s2i/assemble
+if [ -f "/usr/libexec/s2i/assemble" ]; then
+    exec /usr/libexec/s2i/assemble
+elif [ -f "/opt/app-root/src/.s2i/bin/assemble" ]; then
+    exec /opt/app-root/src/.s2i/bin/assemble
+else
+    echo "Error: S2I assemble script not found!"
+    exit 1
+fi
+
